### PR TITLE
:bug: Proper search for tags in Go files only

### LINKED ISSUE #134: Presubmit tests pickup build tags from non-go files (for example, like *.md)
https://github.com/knative/hack/blob/abd085fc43de80d6344a88788ae6b926c48c908e/presubmit-tests.sh#L152-L159

The following code is invalid, as it greps through all the files, no matter the type. That leads to picking tags from files like README.md.

This issue affects https://github.com/knative-sandbox/reconciler-test/pull/273, as the `knative.dev/reconciler-test` package is tested for compilation, but that fails with: 

```
no Go files in /home/ksuszyns/git/reconciler-test
```

/kind bug

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :bug: Proper search for tags in Go files only

/kind bug

Fixes #134

### CODE REVIEW

File: presubmit-tests.sh [hunk 1]
```diff
@@ -138,42 +138,18 @@ function default_build_test_runner() {
...
-      failed=1
-      # Consider an error message everything that's not a successful test result.
-      errors_go2+="$(grep -v '^\(ok\|\?\)\s\+\(github\.com\|knative\.dev\)/' "${report}")"
-    fi
-    # Remove unused generated binary, if any.
-    rm -f e2e.test
-  done
+  tags="$(find . \
+    -path './vendor' -prune -o -path './hack' -prune -o -path './third_party' -prune \
+    -o -type f -name '*.go' -exec grep '// +build' {} + \
```
Comment (dprotaso) [inline presubmit-tests.sh:145]: we probably want to include go1.17 build tag format as well

Comment (dprotaso) [reply presubmit-tests.sh:145]: https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md

Comment (cardil) [reply presubmit-tests.sh:145]: It is not required at this point. But, it will be in the future.

In fact, I'm writing a Go tool to simplify this, and also be included in knobots:

```
tags="$(go run knative.dev/test-infra/tools/go-ls-tags@latest \
  --exclude vendor --exclude third_party --exclude hack)"
```

But, I think that can be delivered with separate PRs

Comment (cardil) [reply presubmit-tests.sh:145]: Here's a draft PR of that tool: https://github.com/knative/test-infra/pull/2995

File: presubmit-tests.sh [hunk 2]
```diff
@@ -138,42 +138,18 @@ function default_build_test_runner() {
...
+    | cut -f3 -d' ' | tr ',' '\n' | uniq | sort | tr '\n' ' ')"
+  report_build_test Build_Go \
+    go test -vet=off -tags "${tags}" -exec echo ./... || failed=2
```
[the remark this answers is not in the document]
Comment (cardil) [reply presubmit-tests.sh:148]: I'm switching here to what is used on Github actions:

https://github.com/knative/.github/blob/main/workflow-templates/knative-go-build.yaml#L64-L65

https://github.com/knative-sandbox/.github/blob/main/workflow-templates/knative-go-build.yaml#L64-L65

File: presubmit-tests.sh [hunk 3]
```diff
@@ -138,42 +138,18 @@ function default_build_test_runner() {
...
 
-  local errors_go
-  errors_go="$(echo -e "${errors_go1}\n${errors_go2}" | uniq)"
-  create_junit_xml _build_tests Build_Go "${errors_go}"
```
[the remark this answers is not in the document]
Comment (cardil) [reply presubmit-tests.sh:173]: Yes

File: presubmit-tests.sh [hunk 4]
```diff
@@ -138,42 +138,18 @@ function default_build_test_runner() {
...
   # Check that we don't have any forbidden licenses in our images.
   subheader "Checking for forbidden licenses"
-  report_build_test Check_Licenses check_licenses || failed=1
+  report_build_test Check_Licenses check_licenses || failed=3
```
[the remark this answers is not in the document]
Comment (cardil) [reply presubmit-tests.sh:152]: Just to get different retcode, to know what failed after it.

**Comment by dprotaso** [comment]
An observation is we don't want to test some of the build flags - ie. tools

ie.  https://github.com/knative/pkg/runs/4786753384?check_suite_focus=true
